[package]
name = "trin-execution"
keywords = ["ethereum", "execution-layer"]
description = "Trin's execution used for gossiping state and soon an execution layer client for Ethereum?"
authors.workspace = true
categories.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
alloy = { workspace = true, features = ["eips", "provider-ipc", "provider-ws", "pubsub", "reqwest", "rpc-types", "rpc-types-engine", "serde", "genesis"] }
alloy-chains = "0.1.51"
alloy-rlp.workspace = true
alloy-rpc-types-engine = { version = "0.4.2", default-features = false, features = ["serde", "jwt", "std"] }
anyhow.workspace = true
async-trait.workspace = true
clap.workspace = true
ethportal-api.workspace = true
ethereum_ssz.workspace = true
ethereum_ssz_derive.workspace = true
e2store.workspace = true
eth_trie.workspace = true
futures-util.workspace = true
hashbrown = "0.14.0"
humanize-duration.workspace = true
http.workspace = true
jsonrpsee = { workspace = true, features = ["async-client", "client", "macros", "server", "server-core"]}
lazy_static.workspace = true
once_cell = "1.17"
parking_lot.workspace = true
pin-project = "1.1.6"
portal-bridge.workspace = true
prometheus_exporter.workspace = true
rand.workspace = true
rayon = "1.10.0"
reqwest =  { workspace = true, features = ["stream"] }
revm.workspace = true
revm-inspectors = "0.8.1"
revm-primitives.workspace = true
rocksdb = "0.22.0"
serde = { workspace = true, features = ["rc"] }
serde_json = { workspace = true, features = ["preserve_order"]}
serde-this-or-that.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true
trin-evm.workspace = true
trin-utils.workspace = true
url.workspace = true

# Trin dependencies
dirs = "5.0.1"
discv5.workspace = true
futures.workspace = true
portalnet.workspace = true
regex = "1.10.2"
reth-ipc.workspace = true
rpc.workspace = true
sha3.workspace = true
tempfile.workspace = true
tracing-subscriber.workspace = true
tree_hash.workspace = true
trin-history.workspace = true
trin-state.workspace = true
trin-storage.workspace = true
trin-validation.workspace = true
utp-rs.workspace = true

[dev-dependencies]
test-log.workspace = true
tracing-test.workspace = true
